---
- hosts: localhost
  gather_facts: no
  tasks:
    - pause:
        prompt: |
          What do you want to see?
            1 - single variable
            2 - all variables
            3 - group variables
            4 - single fact
        echo: yes
      register: debug_option
    - pause:
        prompt: |
          Which variable?
        echo: yes
      register: selected_var
      when: debug_option.user_input == "1"
    - pause:
        prompt: |
          Which fact?
        echo: yes
      register: selected_fact
      when: debug_option.user_input == "4"
    - pause:
        prompt: |
          For which host(s)?
        echo: yes
      register: target_hosts
      when: debug_option.user_input != "3"
    - pause:
        prompt: |
          For which group?
        echo: yes
      register: target_group
      when: debug_option.user_input == "3"
    - block:
        - add_host:
            name: "{{ item }}"
            groups: debug
          loop: "{{ groups[ target_hosts.user_input ] }}"
          changed_when: False
      when:
        - debug_option.user_input != "3"
        - groups[ target_hosts.user_input ] is defined
    - block:
        - add_host:
            name: "{{ target_hosts.user_input }}"
            groups: debug
          changed_when: False
      when:
        - debug_option.user_input != "3"
        - groups[ target_hosts.user_input ] is not defined
    - block:
        - debug:
            msg:
              - "{{ selected_var.user_input }}:"
              - "{{ hostvars[item][selected_var.user_input] | default('NOT DEFINED') }}"
          loop: "{{ groups['debug'] }}"
      when: debug_option.user_input == "1"
    - block:
        - debug:
            var: "{{ hostvars[item] }}"
          loop: "{{ groups['debug'] }}"
      when: debug_option.user_input == "2"
    - debug:
        var: "{{ groups[target_group.user_input] }}"
      when: debug_option.user_input == "3"
    - block:
        - setup:
            gather_subset:
              - "{{ selected_fact.user_input | replace('ansible_', '') }}"
          delegate_to: "{{ item }}"
          delegate_facts: true
          loop: "{{ groups['debug'] }}"
        - debug:
            msg:
             - "{{ selected_fact.user_input }}:"
             - "{{ hostvars[item][selected_fact.user_input] | default('NOT DEFINED') }}"
          loop: "{{ groups['debug'] }}"
      when: debug_option.user_input == "4"

