all:
  vars:
    ansible_user: "{{ vault_ansible_user }}"
    ansible_password: "{{ vault_ansible_user_password }}"
    ansible_become_password: "{{ vault_ansible_user_password }}"
  children:
    # OS Type
    bsd:
      children:
        pfsense:
          hosts:
            midas_array:
    linux:
      children:
        proxmox_host:
          children:
            proxmox_6:
              hosts:
                spacedock:
            proxmox_7:
              hosts:
                utopia_planitia:
        ubuntu:
          hosts:
            memory_alpha:
            memory_beta:
            argus_array:
            holosuite_1:
            holosuite_2:
    # Type
    proxmox_vm:
      hosts:
        memory_alpha:
        epsilon_ix:
        holosuite_1:
        argus_array:
        midas_array:
    raspberry_pi:
      vars:
        ansible_group_priority: 10
      hosts:
        memory_beta:
        holosuite_2:
    # Roles
    zfs:
      hosts:
        argus_array:
        memory_alpha:
        memory_beta:
    nas:
      hosts:
        memory_alpha:
        memory_beta:
    snapraid:
      hosts:
        memory_alpha:
    traefik:
      hosts:
        epsilon_ix:
        memory_alpha:
        argus_array:
    docker:
      vars:
        ansible_group_priority: 10
      hosts:
        memory_alpha:
        argus_array:
    metrics:
      hosts:
        memory_alpha:
        memory_beta:
        argus_array:
        epsilon_ix:
    test_machines:
      hosts:
        holosuite_1:
        holosuite_2: