all:
  children:
    nas:
      hosts:
        memory_alpha:
        memory_beta:
    proxmox_host:
      hosts:
        spacedock:
    proxmox_vm:
      hosts:
        memory_alpha:
    raspberry_pi:
      hosts:
        memory_beta: