all:
  vars:
    ansible_user: "{{ vault_ansible_user }}"
    ansible_password: "{{ vault_ansible_user_password }}"
    ansible_become_password: "{{ vault_ansible_user_password }}"
  children:
    # Type
    proxmox_host:
      children:
        proxmox_8:
          hosts:
            spacedock:
            starbase_375:
            utopia_planitia:
    proxmox_vm:
      hosts:
        memory_alpha:
        memory_beta:
        epsilon_ix:
        # holosuite_1:
        argus_array:
        midas_array:
        # deep_space_9:
    raspberry_pi:
      hosts:
        # holosuite_2:
    pfsense:
      hosts:
        midas_array:
    ubuntu:
      hosts:
        memory_alpha:
        memory_beta:
        argus_array:
        # deep_space_9:
        # holosuite_1:
        # holosuite_2:
    linux:
      children:
        # Roles
        zfs:
          hosts:
            argus_array:
            memory_alpha:
            memory_beta:
        nas:
          hosts:
            memory_alpha:
            memory_beta:
        traefik:
          hosts:
            epsilon_ix:
            memory_alpha:
            argus_array:
        docker:
          vars:
            ansible_group_priority: 10
          hosts:
            memory_alpha:
            argus_array:
        test_machines:
          hosts:
            # holosuite_1:
            # holosuite_2: