all:
  vars:
    ansible_user: "{{ vault_ansible_user }}"
    ansible_password: "{{ vault_ansible_password }}"
    ansible_become_password: "{{ vault_ansible_password }}"
  children:
    # Type
    proxmox_host:
      hosts:
        spacedock:
    proxmox_vm:
      hosts:
        memory_alpha:
        holosuite_1:
    raspberry_pi:
      hosts:
        memory_beta:
        holosuite_2:
        argus_array:
    pfsense:
      hosts:
        midas_array:
    ubuntu:
      hosts:
        memory_alpha:
        memory_beta:
        argus_array:
        holosuite_1:
        holosuite_2:
    linux:
      children:
        # Roles
        zfs:
          hosts:
            argus_array:
          children:
            nas:
              hosts:
                memory_alpha:
                memory_beta:
        docker:
          children:
            traefik:
              hosts:
                memory_alpha:
                argus_array:
        test_machines:
          hosts:
            holosuite_1:
            holosuite_2: