all:
  children:
    nas:
      hosts:
        memory_alpha:
        memory_beta:
    proxmox_host:
      hosts:
        spacedock:
    proxmox_vm:
      hosts:
        memory_alpha:
        holosuite_1:
    raspberry_pi:
      hosts:
        memory_beta:
        holosuite_2:
    test_machines:
      hosts:
        holosuite_1: