---
# Required Galaxy Collections
collections:
  - ansible.posix
  - community.general

# Required Galaxy Roles
roles:
  - name: viasite-ansible.zsh
  - name: robertdebock.update
  - name: robertdebock.reboot
