---
# Required Galaxy Collections
collections:
  - ansible.posix
  - community.general
  - community.docker

# Required Galaxy Roles
roles:
  - name: mrlesmithjr.zfs
    # Default version does not work on Ubuntu on Raspberry Pi (as of 04/03/2021)
    # Using third-party fork instead that allows for override
    # see https://github.com/mrlesmithjr/ansible-zfs/pull/14
    src: https://github.com/alexrashed/ansible-zfs
    version: feature/universe-repo
  - name: bertvv.samba
  - name: exterrestris.wsdd
    src: https://github.com/exterrestris/ansible-role-wsdd
  - name: exterrestris.proxmox_ssl
    src: https://github.com/exterrestris/ansible-role-proxmox-ssl
  - name: ironicbadger.ansible_role_proxmox_nag_removal
    src: https://github.com/IronicBadger/ansible-role-proxmox-nag-removal
  - name: exterrestris.ansible_users
    src: https://github.com/exterrestris/ansible-users
  - name: sprat.ansible_role_mergerfs
    src: https://github.com/sprat/ansible-role-mergerfs
  - name: weareinteractive.ufw
  - name: geerlingguy.docker
  - name: geerlingguy.pip
  - name: ironicbadger.ansible_role_snapraid
    # Using own fork until PRs merged:
    # - https://github.com/IronicBadger/ansible-role-snapraid/pull/5
    # - https://github.com/IronicBadger/ansible-role-snapraid/pull/6
    src: https://github.com/exterrestris/ansible-role-snapraid
    version: main
  - name: alvistack.kernel
  - name: linux-system-roles.cockpit
  - name: exterrestris.sanoid
    src: https://github.com/exterrestris/ansible-role-sanoid
  - name: exterrestris.zsh
    src: https://github.com/exterrestris/ansible-role-zsh
    version: powerlevel10k
  - name: robertdebock.update
  - name: robertdebock.reboot
