---
# Required Galaxy Collections
collections:
  - ansible.posix

# Required Galaxy Roles
roles:
  - name: ironicbadger.ansible_role_proxmox_nag_removal
    src: https://github.com/IronicBadger/ansible-role-proxmox-nag-removal
