---
- hosts: localhost
  connection: local
  become: no
  tasks:
    # Verify this is a WSL environment
    - name: check is WSL
      ansible.builtin.assert:
        that:
          - "lookup('env', 'WSL_DISTRO_NAME') is truthy"
    # Get username
    - ansible.builtin.pause:
        prompt: WSL username
        echo: yes
      register: wsl_username

- hosts: localhost
  become: yes
  gather_facts: no
  connection: local
  tasks:
    # Install packages
    - name: install common packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ common_packages }}"

    # Generate SSH key
    - name: generate ssh key
      ansible.builtin.user:
        name: "{{ wsl_username.user_input }}"
        group: "{{ wsl_username.user_input }}"
        shell: /bin/zsh
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_file: .ssh/id_ed25519

    # Install ZSH Powerlevel10k config
    - name: copy p10k config
      ansible.builtin.copy:
        src: "p10k.zsh"
        dest: "/home/{{ wsl_username.user_input }}/.p10k.zsh"
        owner: "{{ wsl_username.user_input }}"
        group: "{{ wsl_username.user_input }}"
        mode: '0644'
  roles:
    # Install any available package updates
    - role: robertdebock.update
      vars:
        update_reboot: no
      tags: updates

    # Reboot if necessary
    - role: robertdebock.reboot
      tags: updates

    # Set locale
    - role: robertdebock.locale
      vars:
        locale_lang: en_GB.UTF-8

    # Install/configure ZSH
    - role: viasite-ansible.zsh
      vars:
        zsh_user: "{{ wsl_username.user_input }}"

    # Run ssh-agent automatically on login
    - role: ssh_agent
      vars:
        user: "{{ wsl_username.user_input }}"
        ssh_agent_source_files:
          - '.bashrc'
          - '.zshrc.local.pre-p10k'
        ssh_agent_keys:
          - ~/.ssh/id_ed25519