---
- hosts: localhost
  vars:
    ansible_user: "{{ main_user.username }}"
    ansible_become_user: "{{ main_user.username }}"
    ansible_become_password: "{{ vault_main_user_password }}"
  tasks:
    - name: check is WSL
      assert:
        that:
          - "lookup('env', 'WSL_DISTRO_NAME')"

- hosts: localhost
  vars:
    ansible_user: "{{ main_user.username }}"
    ansible_become_user: "{{ main_user.username }}"
    ansible_become_password: "{{ vault_main_user_password }}"
  tasks:
    - name: install common packages
      package:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ common_packages }}"
