---
- hosts: localhost
  vars:
    ansible_user: "{{ main_user.username }}"
    ansible_become_user: "{{ main_user.username }}"
    ansible_become_password: "{{ vault_main_user_password }}"
  tasks:
    # Verify this is a WSL environment
    - name: check is WSL
      assert:
        that:
          - "lookup('env', 'WSL_DISTRO_NAME')"

- hosts: localhost
  vars:
    ansible_user: "{{ main_user.username }}"
    ansible_become_user: "{{ main_user.username }}"
    ansible_become_password: "{{ vault_main_user_password }}"
  tasks:
    # Install packages
    - name: install common packages
      package:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ common_packages }}"
    
    # Install ZSH Powerlevel10k config
    - name: copy p10k config
      copy:
        src: "p10k.zsh"
        dest: "/home/{{ main_user.username }}/.p10k.zsh"
        owner: "{{ main_user.username }}"
        group: "{{ main_user.username }}"
        mode: '0644'
  roles:
    # Install/configure ZSH
    - role: exterrestris.zsh
      vars:
        zsh_user: "{{ main_user.username }}"
    
    # Run ssh-agent automatically on login
    - role: ssh_agent
      vars:
        user: "{{ main_user.username }}"
        source_files:
          - '.bashrc'
          - '.zshrc.local.pre-p10k'