---
- hosts: localhost
  connection: local
  become: no
  tasks:
    # Verify this is a WSL environment
    - name: check is WSL
      assert:
        that:
          - "lookup('env', 'WSL_DISTRO_NAME') is truthy"

- hosts: localhost
  become: yes
  gather_facts: no
  connection: local
  tasks:
    # Install packages
    - name: install common packages
      package:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ common_packages }}"

    # Generate SSH key
    - name: generate ssh key
      ansible.builtin.user:
        name: "{{ main_user.username }}"
        group: "{{ main_user.username }}"
        shell: /bin/zsh
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_file: .ssh/id_ed25519

    # Install ZSH Powerlevel10k config
    - name: copy p10k config
      copy:
        src: "p10k.zsh"
        dest: "/home/{{ main_user.username }}/.p10k.zsh"
        owner: "{{ main_user.username }}"
        group: "{{ main_user.username }}"
        mode: '0644'
  roles:
    # Install any available package updates
    - role: robertdebock.update
      vars:
        update_reboot: no
      tags: updates

    # Reboot if necessary
    - role: robertdebock.reboot
      tags: updates

    # Install/configure ZSH
    - role: viasite-ansible.zsh
      vars:
        zsh_user: "{{ main_user.username }}"

    # Run ssh-agent automatically on login
    - role: ssh_agent
      vars:
        user: "{{ main_user.username }}"
        ssh_agent_source_files:
          - '.bashrc'
          - '.zshrc.local.pre-p10k'
        ssh_agent_keys:
          - ~/.ssh/id_ed25519