- name: check ansible user exists
  command: ssh -o User={{ ansible_user }} -o ConnectTimeout=10 -o PreferredAuthentications=publickey -o PubkeyAuthentication=yes {{ ansible_host }} echo "Worked"
  register: remote
  connection: local
  ignore_errors: yes
  become: false
  changed_when: False
  tags:
    - bootstrap-all

- name: collect credentials
  block:
    - name: collect username
      pause:
          prompt: "Username for {{ inventory_hostname }} ({{ ansible_host }})"
          echo: yes
      register: username_result

    - name: collect password
      pause:
          prompt: "Password for {{ username_result.user_input }}"
          echo: no
      register: password_result

    - name: update creds
      set_fact:
        ansible_user: "{{ username_result.user_input }}"
        ansible_password: "{{ password_result.user_input }}"
        ansible_become_password: "{{ password_result.user_input }}"
  when: remote.failed
  tags:
    - bootstrap-all
