---
- name: configure variables
  block:
    - set_fact:
        sudo_package: pfSense-pkg-sudo
        sudo_group: wheel
        sudoers: /usr/local/etc/sudoers
      when: ansible_distribution == 'FreeBSD' and 'pfSense' in ansible_kernel_version
  tags:
    - bootstrap-new
    - bootstrap-all

- name: check if proxmox
  block:
    - name: get installed packages
      ansible.builtin.package_facts:

    - name: update proxmox repos
      block:
        - name: disable pve enterprise repo
          ansible.builtin.deb822_repository:
            name: pve-enterprise
            types: deb
            uris: "https://enterprise.proxmox.com/{{ ansible_distribution | lower }}/pve"
            signed_by: "/usr/share/keyrings/proxmox-archive-keyring.gpg"
            suites: ["{{ ansible_distribution_release | lower }}"]
            components: [enterprise]
            state: present
            enabled: false
            
        - name: enable pve no subscription repo
          ansible.builtin.deb822_repository:
            name: proxmox
            types: deb
            uris: "http://download.proxmox.com/{{ ansible_distribution | lower }}/pve"
            signed_by: "/usr/share/keyrings/proxmox-archive-keyring.gpg"
            suites: ["{{ ansible_distribution_release | lower }}"]
            components: [pve-no-subscription]
            state: present
            enabled: true

        - name: disable ceph enterprise repo
          ansible.builtin.deb822_repository:
            name: ceph-enterprise
            types: deb
            uris: "https://enterprise.proxmox.com/{{ ansible_distribution | lower }}/ceph-squid"
            signed_by: "/usr/share/keyrings/proxmox-archive-keyring.gpg"
            suites: ["{{ ansible_distribution_release | lower }}"]
            components: [enterprise]
            state: present
            enabled: false
            
        - name: enable ceph no subscription repo
          ansible.builtin.deb822_repository:
            name: ceph
            types: deb
            uris: "http://download.proxmox.com/{{ ansible_distribution | lower }}/ceph-squid"
            signed_by: "/usr/share/keyrings/proxmox-archive-keyring.gpg"
            suites: ["{{ ansible_distribution_release | lower }}"]
            components: [no-subscription]
            state: present
            enabled: true

        - name: update repositories
          ansible.builtin.apt:
            update_cache: true
      when: "'proxmox-ve' in ansible_facts.packages"
  when: ansible_distribution == 'Debian'
  tags:
    - bootstrap-new
    - bootstrap-all

- name: install sudo
  package:
    name: "{{ sudo_package | default('sudo') }}"
    state: present
  tags:
    - bootstrap-new
    - bootstrap-all

- name: ensure sudo group in sudoers
  lineinfile:
    dest: "{{ sudoers | default('/etc/sudoers') }}"
    state: present
    regexp: "^%{{ sudo_group | default('sudo') }}"
    insertbefore: '^#includedir'
    line: "%{{ sudo_group | default('sudo') }} ALL=(ALL) ALL"
    validate: visudo -cf %s
  tags:
    - bootstrap-new
    - bootstrap-all

- name: create ansible group
  group:
    name: "{{ vault_ansible_user_group }}"
    gid: "{{ vault_ansible_user_group_gid }}"
  tags:
    - bootstrap-new
    - bootstrap-all

- name: create ansible user
  user:
    name: "{{ vault_ansible_user }}"
    uid: "{{ vault_ansible_user_uid }}"
    group: "{{ vault_ansible_user_group }}"
    groups: "{{ sudo_group | default('sudo') }}"
    password: "{{ vault_ansible_user_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
  tags:
    - bootstrap-new
    - bootstrap-all

- name: add SSH authorized_keys
  authorized_key:
    user: "{{ vault_ansible_user }}"
    key: "{{ item }}"
  with_items: "{{ vault_ansible_user_authorised_keys }}"
  tags:
    - bootstrap-new
    - bootstrap-all
