- name: install sudo
  package:
    name: sudo
    state: present
  tags: setup

- name: create ansible group
  group:
    name: "{{ vault_ansible_user_group }}"
  tags: setup

- name: create ansible user
  user:
    name: "{{ vault_ansible_user }}"
    group: "{{ vault_ansible_user_group }}"
    groups: "sudo"
    password: "{{ vault_ansible_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
  tags: setup

- name: add SSH authorized_keys from github
  authorized_key:
    user: "{{ vault_ansible_user }}"
    key: "https://github.com/{{ vault_ansible_user_github_user }}.keys"
  tags: setup