--- 
- name: configure variables
  block:
    - set_fact:
        sudo_package: pfSense-pkg-sudo
        sudo_group: wheel
        sudoers: /usr/local/etc/sudoers
      when: ansible_distribution == 'FreeBSD' and 'pfSense' in ansible_kernel_version
  tags:
    - bootstrap-new
    - bootstrap-all

- name: install sudo
  package:
    name: "{{ sudo_package | default('sudo') }}"
    state: present
  tags:
    - bootstrap-new
    - bootstrap-all

- name: ensure sudo group in sudoers
  lineinfile:
    dest: "{{ sudoers | default('/etc/sudoers') }}"
    state: present
    regexp: "^%{{ sudo_group | default('sudo') }}"
    insertbefore: '^#includedir'
    line: "%{{ sudo_group | default('sudo') }} ALL=(ALL) ALL"
    validate: visudo -cf %s
  tags:
    - bootstrap-new
    - bootstrap-all

- name: create ansible group
  group:
    name: "{{ vault_ansible_user_group }}"
    gid: "{{ vault_ansible_user_group_gid }}"
  tags:
    - bootstrap-new
    - bootstrap-all

- name: create ansible user
  user:
    name: "{{ vault_ansible_user }}"
    uid: "{{ vault_ansible_user_uid }}"
    group: "{{ vault_ansible_user_group }}"
    groups: "{{ sudo_group | default('sudo') }}"
    password: "{{ vault_ansible_user_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
  tags:
    - bootstrap-new
    - bootstrap-all

- name: add SSH authorized_keys from github
  authorized_key:
    user: "{{ vault_ansible_user }}"
    key: "https://github.com/{{ vault_ansible_user_github_user }}.keys"
  tags:
    - bootstrap-new
    - bootstrap-all