---
main_user:
  username: sean
  generate_ssh_key: yes
  generate_ssh_key_type: ed25519
  generate_ssh_key_file: .ssh/id_ed25519

common_packages:
  - name: htop
  - name: ncdu
  - name: python3
  - name: python3-pip
  - name: fzf
  - name: unzip
  - name: zsh
  - name: tree

### viasite-ansible.zsh
zsh_antigen_theme: "romkatv/powerlevel10k powerlevel10k"

zsh_powerlevel10k_instant_prompt: yes

zsh_powerlevel_custom_elements:

zsh_antigen_bundles:
  - { name: command-not-found }
  - { name: docker, command: docker }
  - { name: docker-compose, command: docker-compose }
  - fancy-ctrl-z
  - git-extras
  - gnu-utils
  - { name: httpie, command: http }
  - { name: golang, command: go }
  - { name: gulp, command: gulp }
  - { name: helm, command: helm }
  - { name: pip, command: pip }
  - { name: rake, command: rake }
  - { name: systemd, command: systemctl }
  - python
  - { name: tmux, command: tmux }
  - { name: vagrant, command: vagrant }
  - { name: zsh-users/zsh-autosuggestions }
  - { name: unixorn/autoupdate-antigen.zshplugin }
  - urbainvaes/fzf-marks
  - ytet5uy4/fzf-widgets
  - { name: zdharma/fast-syntax-highlighting@v1.2 }

zsh_editor: nano

zsh_aliases: []

zsh_path:
  - "{{ zsh_fzf_path }}"
  - /usr/local/sbin
  - /usr/local/bin
  - $HOME/.local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
