---
ansible_user: "{{ vault_ansible_user }}"
ansible_password: "{{ vault_ansible_password }}"
ansible_become_password: "{{ vault_ansible_password }}"

main_user:
  username: sean
  name: Sean Ellingham
  password: "{{ vault_main_user_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
  update_password: on_create
  groups:
    - 'sudo'
  github_username: exterrestris
  uid: "1000"
  gid: "1000"
  samba:
    name: Sean
    password: "{{ vault_main_user_password }}"

common_packages:
  - name: htop
  - name: ncdu
  - name: python3
  - name: python3-pip

internal_domain: "{{ vault_domain }}"