---
ansible_user: "{{ vault_ansible_user }}"
ansible_password: "{{ vault_ansible_password }}"
ansible_become_password: "{{ vault_ansible_password }}"

main_username: sean
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"

common_packages:
  - name: htop
  - name: ncdu
  - name: python3
  - name: python3-pip

internal_domain: "{{ vault_domain }}"