---
target_os: debian #proxmox

proxmox_additional_packages:
  - name: lshw
  - name: lm-sensors
  - name: smartmontools
  - name: nvme-cli

proxmox_ssl_certificate_source: certmate
proxmox_ssl_certmate_token: "{{ vault_certmate_api_token }}"
proxmox_ssl_certmate_host: "certmate.{{ internal_domain }}"
proxmox_ssl_certmate_cert: "{{ internal_domain }}"
proxmox_ssl_run_now: yes
