---
target_os: debian #proxmox

proxmox_ssl_ssh_host: "midas-array.{{ internal_domain }}"
proxmox_ssl_ssh_user: admin
proxmox_ssl_ssh_host_python: "{{ hostvars['midas_array']['ansible_python_interpreter'] }}"
proxmox_ssl_ssh_cert_path: "/conf/acme/{{ internal_domain }}-wildcard.fullchain"
proxmox_ssl_ssh_key_path: "/conf/acme/{{ internal_domain }}-wildcard.key"
proxmox_ssl_ssh_add_remote_to_known_hosts: yes
proxmox_ssl_run_now: yes
