---
ansible_host: 192.168.5.132
target_os: ubuntu

scans_user:
  username: scans
  password: "{{ vault_scans_user_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
  group: scans
  samba:
    name: Scans
    password: "{{ vault_scans_user_password }}"

### mrlesmithjr.zfs
zfs_pools:
  - name: pool1
    action: 'create'
    compression: 'lz4'
    devices:
      - 'scsi-SATA_WDC_WD120EMAZ-11_8CKANMKF'
      - 'scsi-SATA_WDC_WD120EMAZ-11_8CKATPYE'
    type: 'mirror'
    state: 'present'
  - name: pool2
    action: 'create'
    compression: 'lz4'
    devices:
      - 'scsi-SATA_WDC_WD60EZRZ-00G_WD-WX41D95A2NJL'
      - 'scsi-SATA_WDC_WD60EZRZ-00R_WD-WX11DB56ZP10'
    type: 'mirror'
    state: 'present'

zfs_filesystems:
  - name: backups
    pool: pool1
    compression: lz4
    mountpoint: /mnt/zfs/backups
    state: present
  - name: backups/computers
    pool: pool1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/computers
    state: present
  - name: backups/drives
    pool: pool1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/drives
    state: present
  - name: backups/files
    pool: pool1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/files
    state: present
  - name: archive
    pool: pool1
    compression: lz4
    mountpoint: /mnt/zfs/archive
    state: present
  - name: resources
    pool: pool2
    compression: lz4
    mountpoint: /mnt/zfs/resources
    state: present

### mount_disks
parity_disks:
  - path: /mnt/ext4/parity1
    diskbyid: /dev/disk/by-uuid/13a02c9d-1344-4523-9238-a6757142f6ae
    fs: ext4
    opts: defaults
    content: true

data_disks:
  - path: /mnt/ext4/data1
    diskbyid: /dev/disk/by-uuid/3eee8a73-449f-4680-ac95-a88226b27d79
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/data2
    diskbyid: /dev/disk/by-uuid/7f6e6993-8f06-4cf4-8f59-ec0ba5771bea
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/data3
    diskbyid: /dev/disk/by-uuid/f4ca6d24-5142-4583-adc4-ae791f25b4ca
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/data4
    diskbyid: /dev/disk/by-uuid/56eb9377-2ddc-4fc3-8409-d7549d4a0dab
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/data5
    diskbyid: /dev/disk/by-uuid/e0e41243-f51b-4730-a9c7-c001279a7315
    fs: ext4
    opts: defaults
    content: true

other_disks:
  - path: /mnt/ext4/transient1
    diskbyid: /dev/disk/by-uuid/cade8c26-973a-4ff1-9669-36fbcde5b97c
    fs: ext4
    opts: defaults
  - path: /mnt/ext4/transient2
    diskbyid: /dev/disk/by-uuid/d8fb93fb-4c74-4e21-b005-942d5cd89e58
    fs: ext4
    opts: defaults

ntfs_data_disks:

other_mounts:
  - path: /mnt/zfs

remove_mounts:

### sprat.ansible-role-mergerfs
mergerfs_mounts:
  - path: /mnt/storage
    branches:
      - /mnt/ext4/data*
    options: "{{ mergerfs_opts }},category.create={{ mergerfs_policy }},x-systemd.requires=/mnt/ext4/data1,x-systemd.requires=/mnt/ext4/data2,x-systemd.requires=/mnt/ext4/data3"
  - path: /mnt/transient
    branches:
      - /mnt/ext4/transient*
    options: "{{ mergerfs_opts }},category.create={{ mergerfs_policy }},x-systemd.requires=/mnt/ext4/transient1"

### bertvv.samba
samba_shares:
  - name: Archive
    path: /mnt/zfs/archive
    owner: "{{ main_user.username }}"
    group: archive
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
  - name: Backups
    path: /mnt/zfs/backups
    owner: "{{ main_user.username }}"
    group: backups
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
  - name: Media
    path: /mnt/storage/Media
    owner: "{{ main_user.username }}"
    group: media
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
  - name: Resources
    path: /mnt/zfs/resources
    owner: "{{ main_user.username }}"
    group: resources
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
  - name: Downloads
    path: /mnt/transient/Downloads
    owner: "{{ main_user.username }}"
    group: downloads
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
    browseable: 'yes'
  - name: Scans
    path: /mnt/transient/Scans
    owner: "{{ scans_user.username }}"
    group: "{{ scans_user.group }}"
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
    browseable: 'yes'

### ironicbadger.ansible_role_snapraid
snapraid_email_address: "memory-alpha@{{ internal_domain }}"
