---
target_os: ubuntu

users:
  - username: sean
    name: Sean Ellingham
    groups:
      - 'sudo'
      - 'backups'
      - 'media'
      - 'scans'
      - 'archive'
      - 'resources'
    github_username: exterrestris
    password: $6$CVT.SP2GSSu/sbE7$KioDey0lx2KQ3KLoTuylnCwoIFnTkO9gc169sSOn1MePHjs6MBzI/E38qkJ6Hq0mYtYODrcLvZM8iqnkhbGh01
    update_password: on_create
  - username: scans
    group: scans

groups_to_create:
  - name: backups
  - name: media
  - name: archive
  - name: downloads
  - name: resources
  - name: scans

zfs_create_pools: true

zfs_pools:
  - name: pool1
    action: 'create'
    compression: 'lz4'
    devices:
      - 'scsi-SATA_WDC_WD120EMAZ-11_8CKANMKF'
      - 'scsi-SATA_WDC_WD120EMAZ-11_8CKATPYE'
    type: 'mirror'
    state: 'present'
  - name: pool2
    action: 'create'
    compression: 'lz4'
    devices:
      - 'scsi-SATA_WDC_WD60EZRZ-00G_WD-WX41D95A2NJL'
      - 'scsi-SATA_WDC_WD60EZRZ-00R_WD-WX11DB56ZP10'
    type: 'mirror'
    state: 'present'

zfs_create_filesystems: true

zfs_filesystems:
  - name: backups
    pool: pool1
    compression: lz4
    mountpoint: /mnt/zfs/backups
    state: present
  - name: backups/computers
    pool: pool1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/computers
    state: present
  - name: backups/drives
    pool: pool1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/drives
    state: present
  - name: backups/files
    pool: pool1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/files
    state: present
  - name: archive
    pool: pool1
    compression: lz4
    mountpoint: /mnt/zfs/archive
    state: present
  - name: resources
    pool: pool2
    compression: lz4
    mountpoint: /mnt/zfs/resources
    state: present

btrfs_data_opts: compress=zstd

parity_disks:
  - path: /mnt/ext4/parity1
    diskbyid: /dev/disk/by-uuid/13a02c9d-1344-4523-9238-a6757142f6ae
    fs: ext4
    opts: defaults
    content: true

data_disks:
  - path: /mnt/ext4/data1
    diskbyid: /dev/disk/by-uuid/3eee8a73-449f-4680-ac95-a88226b27d79
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/data2
    diskbyid: /dev/disk/by-uuid/7f6e6993-8f06-4cf4-8f59-ec0ba5771bea
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/data3
    diskbyid: /dev/disk/by-uuid/f4ca6d24-5142-4583-adc4-ae791f25b4ca
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/data4
    diskbyid: /dev/disk/by-uuid/56eb9377-2ddc-4fc3-8409-d7549d4a0dab
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/data5
    diskbyid: /dev/disk/by-uuid/e0e41243-f51b-4730-a9c7-c001279a7315
    fs: ext4
    opts: defaults
    content: true

other_disks:
  - path: /mnt/ext4/transient1
    diskbyid: /dev/disk/by-uuid/cade8c26-973a-4ff1-9669-36fbcde5b97c
    fs: ext4
    opts: defaults
  - path: /mnt/ext4/transient2
    diskbyid: /dev/disk/by-uuid/d8fb93fb-4c74-4e21-b005-942d5cd89e58
    fs: ext4
    opts: defaults

ntfs_opts: nls=utf8,umask=0022,uid=1000

ntfs_data_disks:

other_mounts:
  - path: /mnt/zfs

remove_mounts:
  - path: /mnt/btrfs/transient1
  - path: /mnt/btrfs/transient2

# sprat.ansible-role-mergerfs
mergerfs_opts: allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.create=mfs

mergerfs_mounts:
  - path: /mnt/storage
    branches:
      - /mnt/ext4/data*
    options: "{{ mergerfs_opts }},x-systemd.requires=/mnt/ext4/data1,x-systemd.requires=/mnt/ext4/data2,x-systemd.requires=/mnt/ext4/data3"
  - path: /mnt/transient
    branches:
      - /mnt/ext4/transient*
    options: "{{ mergerfs_opts }},x-systemd.requires=/mnt/ext4/transient1"

# bertvv.samba
samba_workgroup: FEDERATION
samba_preferred_master: true

samba_users: "{{ vault_samba_users }}"

# Handle Windows not being able to browse shares due to incorrectly applied mitigation (https://github.com/bertvv/ansible-role-samba/issues/62)
samba_mitigate_cve_2017_7494: false

samba_shares:
  - name: Archive
    path: /mnt/zfs/archive
    owner: sean
    group: archive
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
  - name: Backups
    path: /mnt/zfs/backups
    owner: sean
    group: backups
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
  - name: Media
    path: /mnt/storage/Media
    owner: sean
    group: media
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
  - name: Resources
    path: /mnt/zfs/resources
    owner: sean
    group: resources
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
  - name: Downloads
    path: /mnt/transient/Downloads
    owner: sean
    group: downloads
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
    browseable: 'yes'
  - name: Scans
    path: /mnt/transient/Scans
    owner: scans
    group: scans
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
    browseable: 'yes'

wsdd_workgroup: "{{ samba_workgroup }}"

ufw_rules:
  - rule: allow
    name: OpenSSH
  - rule: allow
    name: Samba

# ironicbadger.ansible_role_snapraid
snapraid_email_address: "memory-alpha@{{ internal_domain }}"
snapraid_gmail_pass: "{{ vault_snapraid_email_password }}"
snapraid_email_address_to: "{{ vault_snapraid_email_to }}"
snapraid_email_sendon: "success,error"

snapraid_smtp_host: smtp.migadu.com

snapraid_run_command: "python3 {{ snapraid_run_bin }} -c {{ snapraid_run_conf}} > /dev/null"
snapraid_run_scrub_percent: 25
snapraid_run_scrub_age: 10