---
target_os: ubuntu

users:
  - username: sean
    name: Sean Ellingham
    groups:
      - 'sudo'
      - 'backups'
      - 'media'
    github_username: exterrestris
    password: $6$CVT.SP2GSSu/sbE7$KioDey0lx2KQ3KLoTuylnCwoIFnTkO9gc169sSOn1MePHjs6MBzI/E38qkJ6Hq0mYtYODrcLvZM8iqnkhbGh01
    update_password: on_create

groups_to_create:
  - name: backups
  - name: media

zfs_create_pools: true

zfs_pools:
  - name: pool1
    action: 'create'
    compression: 'lz4'
    devices:
      - 'scsi-SATA_WDC_WD120EMAZ-11_8CKANMKF'
      - 'scsi-SATA_WDC_WD120EMAZ-11_8CKATPYE'
    type: 'mirror'
    state: 'present'
  - name: pool2
    action: 'create'
    compression: 'lz4'
    devices:
      - 'scsi-SATA_WDC_WD60EZRZ-00G_WD-WX41D95A2NJL'
      - 'scsi-SATA_WDC_WD60EZRZ-00R_WD-WX11DB56ZP10'
    type: 'mirror'
    state: 'present'

zfs_create_filesystems: true

zfs_filesystems:
  - name: backups
    pool: pool1
    compression: lz4
    mountpoint: /mnt/zfs/backups
    state: present
  - name: backups/computers
    pool: pool1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/computers
    state: present
  - name: backups/drives
    pool: pool1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/drives
    state: present
  - name: backups/files
    pool: pool1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/files
    state: present
  - name: archive
    pool: pool1
    compression: lz4
    mountpoint: /mnt/zfs/archive
    state: present
  - name: resources
    pool: pool2
    compression: lz4
    mountpoint: /mnt/zfs/resources
    state: present

btrfs_data_opts: compress=zstd

parity_disks:
  - { path: /mnt/btrfs/parity1, diskbyid: /dev/disk/by-uuid/8f19d4c7-6246-4f0e-aa91-22bb85a9617c, fs: btrfs, opts: defaults }

data_disks:
  - { path: /mnt/btrfs/data4, diskbyid: /dev/disk/by-uuid/da970999-ae30-49ca-a8b9-51cd8d187e00, fs: btrfs, opts: "{{ btrfs_data_opts }}" }

ntfs_opts: nls=utf8,umask=0022,uid=1000

ntfs_data_disks:
  - { path: /mnt/ntfs/data1, diskbyid: /dev/disk/by-uuid/01D5A8BCC7A78420, fs: ntfs, opts: "{{ ntfs_opts}}" }
  - { path: /mnt/ntfs/data2, diskbyid: /dev/disk/by-uuid/01D639B01A6E6C80, fs: ntfs, opts: "{{ ntfs_opts}}" }
  - { path: /mnt/ntfs/data5, diskbyid: /dev/disk/by-uuid/01D59697B6B37520, fs: ntfs, opts: "{{ ntfs_opts}}" }

ntfs_other_disks:
  - { path: /mnt/ntfs/transient1, diskbyid: /dev/disk/by-uuid/01D703DF4EA1B5D0, fs: ntfs, opts: "{{ ntfs_opts}}" }
  - { path: /mnt/ntfs/transient4, diskbyid: /dev/disk/by-uuid/01D703D85BFBB200, fs: ntfs, opts: "{{ ntfs_opts}}" }

other_mounts:
  - path: /mnt/zfs

remove_mounts:
  - path: /mnt/ntfs/data3
  - path: /mnt/ntfs/data4
  - path: /mnt/ntfs/data6
  - path: /mnt/ntfs/data7
  - path: /mnt/ntfs/data8
  - path: /mnt/ntfs/landing1
  - path: /mnt/ntfs/landing2
  - path: /mnt/ntfs/transient2
  - path: /mnt/ntfs/transient3

# sprat.ansible-role-mergerfs
mergerfs_mounts:
  - path: /mnt/storage
    branches:
      - /mnt/ntfs/data*/PoolPart.*/PoolPart.*
      - /mnt/ntfs/landing*/PoolPart.*/PoolPart.*
      - /mnt/btrfs/data*/data
    options: allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.create=mfs,x-systemd.requires=/mnt/ntfs/data1,x-systemd.requires=/mnt/ntfs/landing1
  - path: /mnt/transient
    branches:
      - /mnt/ntfs/transient*/PoolPart.*
    options: allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.create=mfs,x-systemd.requires=/mnt/ntfs/transient1

# bertvv.samba
samba_workgroup: FEDERATION
samba_preferred_master: true

samba_users: "{{ vault_samba_users }}"

# Handle Windows not being able to browse shares due to incorrectly applied mitigation (https://github.com/bertvv/ansible-role-samba/issues/62)
samba_mitigate_cve_2017_7494: false

samba_shares:
  - name: Archive
    path: /mnt/zfs/archive
    read_only: no
    guest_ok: 'yes'
  - name: Backups
    path: /mnt/zfs/backups
    read_only: no
    guest_ok: 'yes'
  - name: Media
    path: /mnt/storage/Media
    read_only: no
    guest_ok: 'yes'
  - name: Resources
    path: /mnt/zfs/resources
    read_only: no
    guest_ok: 'yes'
  - name: Compressed Files
    path: /mnt/transient/Compressed Files
    read_only: no
    guest_ok: 'yes'
  - name: Downloads
    path: /mnt/transient/Downloads
    read_only: no
    guest_ok: 'yes'
    browseable: 'yes'
  - name: Scans
    path: /mnt/transient/Scans
    read_only: no
    guest_ok: 'yes'
    browseable: 'yes'

wsdd_workgroup: "{{ samba_workgroup }}"

ufw_rules:
  - rule: allow
    name: OpenSSH
  - rule: allow
    name: Samba
