---
ansible_host: 192.168.5.132
target_os: ubuntu

users:
  - username: sean
    name: Sean Ellingham
    groups:
      - 'sudo'
      - 'backups'
      - 'media'
      - 'scans'
      - 'archive'
      - 'resources'
    github_username: exterrestris
    password: $6$CVT.SP2GSSu/sbE7$KioDey0lx2KQ3KLoTuylnCwoIFnTkO9gc169sSOn1MePHjs6MBzI/E38qkJ6Hq0mYtYODrcLvZM8iqnkhbGh01
    update_password: on_create
  - username: scans
    group: scans

groups_to_create:
  - name: backups
  - name: media
  - name: archive
  - name: downloads
  - name: resources
  - name: scans

### mrlesmithjr.zfs
zfs_pools:
  - name: pool1
    action: 'create'
    compression: 'lz4'
    devices:
      - 'scsi-SATA_WDC_WD120EMAZ-11_8CKANMKF'
      - 'scsi-SATA_WDC_WD120EMAZ-11_8CKATPYE'
    type: 'mirror'
    state: 'present'
  - name: pool2
    action: 'create'
    compression: 'lz4'
    devices:
      - 'scsi-SATA_WDC_WD60EZRZ-00G_WD-WX41D95A2NJL'
      - 'scsi-SATA_WDC_WD60EZRZ-00R_WD-WX11DB56ZP10'
    type: 'mirror'
    state: 'present'

zfs_filesystems:
  - name: backups
    pool: pool1
    compression: lz4
    mountpoint: /mnt/zfs/backups
    state: present
  - name: backups/computers
    pool: pool1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/computers
    state: present
  - name: backups/drives
    pool: pool1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/drives
    state: present
  - name: backups/files
    pool: pool1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/files
    state: present
  - name: archive
    pool: pool1
    compression: lz4
    mountpoint: /mnt/zfs/archive
    state: present
  - name: resources
    pool: pool2
    compression: lz4
    mountpoint: /mnt/zfs/resources
    state: present

### mount_disks
parity_disks:
  - path: /mnt/ext4/parity1
    diskbyid: /dev/disk/by-uuid/13a02c9d-1344-4523-9238-a6757142f6ae
    fs: ext4
    opts: defaults
    content: true

data_disks:
  - path: /mnt/ext4/data1
    diskbyid: /dev/disk/by-uuid/3eee8a73-449f-4680-ac95-a88226b27d79
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/data2
    diskbyid: /dev/disk/by-uuid/7f6e6993-8f06-4cf4-8f59-ec0ba5771bea
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/data3
    diskbyid: /dev/disk/by-uuid/f4ca6d24-5142-4583-adc4-ae791f25b4ca
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/data4
    diskbyid: /dev/disk/by-uuid/56eb9377-2ddc-4fc3-8409-d7549d4a0dab
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/data5
    diskbyid: /dev/disk/by-uuid/e0e41243-f51b-4730-a9c7-c001279a7315
    fs: ext4
    opts: defaults
    content: true

other_disks:
  - path: /mnt/btrfs/transient1
    diskbyid: /dev/disk/by-uuid/037cc6ff-80e9-4de1-9b7c-6b7ec7fff069
    fs: btrfs
    opts: "{{ btrfs_data_opts }}"
  - path: /mnt/btrfs/transient2
    diskbyid: /dev/disk/by-uuid/6be7a406-89a3-462c-aee4-1c3036ab1cf2
    fs: btrfs
    opts: "{{ btrfs_data_opts }}"

ntfs_data_disks:

other_mounts:
  - path: /mnt/zfs

remove_mounts:

### sprat.ansible-role-mergerfs
mergerfs_mounts:
  - path: /mnt/storage
    branches:
      - /mnt/ext4/data*
    options: "{{ mergerfs_opts }},x-systemd.requires=/mnt/ext4/data1,x-systemd.requires=/mnt/ext4/data2,x-systemd.requires=/mnt/ext4/data3"
  - path: /mnt/transient
    branches:
      - /mnt/btrfs/*/transient
    options: "{{ mergerfs_opts }},x-systemd.requires=/mnt/btrfs/parity1"

### bertvv.samba
samba_shares:
  - name: Archive
    path: /mnt/zfs/archive
    owner: sean
    group: archive
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
  - name: Backups
    path: /mnt/zfs/backups
    owner: sean
    group: backups
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
  - name: Media
    path: /mnt/storage/Media
    owner: sean
    group: media
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
  - name: Resources
    path: /mnt/zfs/resources
    owner: sean
    group: resources
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
  - name: Compressed Files
    path: /mnt/transient/Compressed Files
    writable: 'yes'
    guest_ok: 'yes'
  - name: Downloads
    path: /mnt/transient/Downloads
    owner: sean
    group: downloads
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
    browseable: 'yes'
  - name: Scans
    path: /mnt/transient/Scans
    owner: scans
    group: scans
    mode: '2775'
    writable: 'yes'
    guest_ok: 'yes'
    browseable: 'yes'

### ironicbadger.ansible_role_snapraid
snapraid_email_address: "memory-alpha@{{ internal_domain }}"
