---
ansible_host: 192.168.5.148
target_os: ubuntu

### mrlesmithjr.zfs
zfs_pools:
  - name: backup1
    action: create
    import: force
    compression: 'lz4'
    type: 'raidz2'
    devices:
      # WD60EZRZ WD-WX11DB56ZP10 (6TB)
      - 'wwn-0x50014ee20d782122'
      # WD60PURZ WD-WX92DA0N82VF (6TB)
      - 'wwn-0x50014ee2147bff7f'
      # WD60EZRZ WD-WX41D95A2NJL (6TB)
      - 'wwn-0x50014ee2621c4a10'
      # WD63PURZ WD-WX62D22N9A9E (6TB)
      - 'wwn-0x50014ee26a7cbb95'
      # ST6000VX001 WSC057K7 (6TB)
      - 'wwn-0x5000c500d55abe86'
      # WD60PURX WD-WX22D70EJRDF (6TB)
      - 'wwn-0x50014ee2bdc2c37a'
      # MG08ADA6 7450A07NFD0H (6TB)
      - 'wwn-0x5000039d68c973f7'
      # WD64PURZ WD-WX52DA31RU5U (6TB)
      - 'wwn-0x50014ee26b7f3af9'
      # WD62PURZ WD-C80DD0PG (6TB)
      - 'wwn-0x50014ee213a9708f'
    properties:
      ashift: 12
      autoexpand: 'on'
    state: 'present'
  - name: backup1
    action: add
    compression: 'lz4'
    type: 'special mirror'
    devices:
      # INTEL SSDSC2KB24 BTYF935307WW240AGN (240GB)
      - 'wwn-0x55cd2e41515ecfa8'
      # INTEL SSDSC2BB16 PHWL510301K5160MGN (160GB) (temp)
      - 'wwn-0x55cd2e404c4f1b94'
      # INTEL SSDSC2BX48 BTHC629309CD480MGN (480GB) (temp)
      - 'wwn-0x55cd2e404c2892c5'
    state: 'present'

zfs_filesystems:
  - name: memory-alpha
    pool: backup1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/backups/memory-alpha
    state: present
  - name: argus-array
    pool: backup1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/backups/argus-array
    state: present

### exterrestris.sanoid
sanoid_datasets:
  - name: backup1/memory-alpha
    templates: backups
    recursive: yes
  - name: backup1/argus-array
    templates: backups
    recursive: yes

### mount_disks
parity_disks:
data_disks:
other_disks:
ntfs_data_disks:

other_mounts:
  - path: /mnt/zfs
  - path: /mnt/backups

remove_mounts:

### tigattack.mergerfs
mergerfs_mounts: []

### vladgh.samba.server
samba_shares: []
