---
ansible_host: 192.168.5.148
target_os: ubuntu

### mrlesmithjr.zfs
zfs_pools:
  - name: backup1
    action: create
    import: force
    compression: 'lz4'
    type: 'raidz2'
    devices:
      # WDC_WD60EZRZ-00G_WD-WX11DB56ZP10
      - 'wwn-0x50014ee20d782122'
      # ST8000DM004 WCT1ENP6
      - 'wwn-0x5000c500bfefa856'
      # ST8000DM004 WCT1NW5D
      - 'wwn-0x5000c500c00d866a'
      # ST8000DM004 WCT2EN1H
      - 'wwn-0x5000c500cc5bcf93'
      # ST8000DM004 WCT1LZ42
      - 'wwn-0x5000c500bffc5046'
      # ST8000DM004 WCT00CM0
      - 'wwn-0x5000c500a9cb6ac5'
    properties:
      ashift: 12
      autoexpand: 'on'
    options:
      - '-f' # Need to force as disks are different sizes
    state: 'present'

zfs_filesystems:
  - name: memory-alpha
    pool: backup1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/backups/memory-alpha
    state: present
  - name: argus-array
    pool: backup1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/backups/argus-array
    state: present

### exterrestris.sanoid
sanoid_datasets:
  - name: backup1/archive
    templates: backups
  - name: backup1/backups/memory-alpha
    templates: backups
  - name: backup1/backups/memory-alpha/computers
    templates: backups
  - name: backup2/backups/memory-alpha
    templates: backups
  - name: backup2/backups/memory-alpha/appdata
    templates: backups
  - name: backup2/backups/memory-alpha/drives
    templates: backups
  - name: backup2/backups/memory-alpha/photos
    templates: backups

### mount_disks
parity_disks:
data_disks:
other_disks:
ntfs_data_disks:

other_mounts:
  - path: /mnt/zfs
  - path: /mnt/backups

remove_mounts:

### tigattack.mergerfs
mergerfs_mounts: []

### bertvv.samba
samba_shares: []
