---
target_os: ubuntu

users:
  - username: sean
    name: Sean Ellingham
    groups:
      - 'sudo'
      - 'backups'
      - 'media'
      - 'scans'
      - 'archive'
      - 'resources'
    github_username: exterrestris
    password: $6$CVT.SP2GSSu/sbE7$KioDey0lx2KQ3KLoTuylnCwoIFnTkO9gc169sSOn1MePHjs6MBzI/E38qkJ6Hq0mYtYODrcLvZM8iqnkhbGh01
    update_password: on_create
  - username: scans
    group: scans

groups_to_create:
  - name: backups
  - name: media
  - name: archive
  - name: downloads
  - name: resources
  - name: scans

zfs_ubuntu_universe_repo_url: http://ports.ubuntu.com/ubuntu-ports

zfs_create_pools: true

zfs_pools:
  - name: backup1
    action: 'create'
    compression: 'lz4'
    devices:
      # USB dock doesn't expose disk IDs - using partition UUIDs
      - '1d63c541-3a7b-45ce-a2a2-dc96cecf8d11'
      - 'c2101a06-81ad-4194-b32f-3962b92b9b00'
    type: 'mirror'
    state: 'present'

zfs_create_filesystems: true

zfs_filesystems:
  - name: backups
    pool: backup1
    compression: lz4
    mountpoint: /mnt/zfs/backups
    state: present
  - name: backups/computers
    pool: backup1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/computers
    state: present
  - name: backups/drives
    pool: backup1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups/drives
    state: present
  - name: archive
    pool: backup1
    compression: lz4
    mountpoint: /mnt/zfs/archive
    state: present

parity_disks:
  - path: /mnt/ext4/parity1
    diskbyid: /dev/disk/by-uuid/a8a450d1-c9cd-4a9d-a904-138b793e5135
    fs: ext4
    opts: defaults

data_disks:
  - path: /mnt/ext4/backups1
    diskbyid: /dev/disk/by-uuid/e5a631ba-6896-46d8-a947-aec2a745e697
    fs: ext4
    opts: defaults
  - path: /mnt/ext4/backups2
    diskbyid: /dev/disk/by-uuid/e9585a85-0247-4d0d-ae2c-cb5e83fea1eb
    fs: ext4
    opts: defaults

other_disks:

ntfs_data_disks:

other_mounts:
  - path: /mnt/zfs

remove_mounts:

# sprat.ansible-role-mergerfs
mergerfs_opts: allow_other,use_ino,cache.files=off,dropcacheonclose=true,category.create=mfs

mergerfs_mounts:
  - path: /mnt/backups
    branches:
      - /mnt/ext4/backups*/data
    options: "{{ mergerfs_opts }},x-systemd.requires=/mnt/ext4/backups1,x-systemd.requires=/mnt/ext4/backups2"
