---
ansible_host: 192.168.5.148
target_os: ubuntu

### mrlesmithjr.zfs
zfs_pools:
  - name: backup1
    action: create
    import: force
    compression: 'lz4'
    type: 'raidz2'
    devices:
      # WD60EZRZ WD-WX11DB56ZP10 (6TB)
      - 'wwn-0x50014ee20d782122'
      # WD60PURZ WD-WX92DA0N82VF (6TB)
      - 'wwn-0x50014ee2147bff7f'
      # WD60EZRZ WD-WX41D95A2NJL (6TB)
      - 'wwn-0x50014ee2621c4a10'
      # WD63PURZ WD-WX62D22N9A9E (6TB)
      - 'wwn-0x50014ee26a7cbb95'
      # ST6000VX001 WSC057K7 (6TB)
      - 'wwn-0x5000c500d55abe86'
      # WD60PURX WD-WX22D70EJRDF (6TB)
      - 'wwn-0x50014ee2bdc2c37a'
    properties:
      ashift: 12
      autoexpand: 'on'
    state: 'present'

zfs_filesystems:
  - name: memory-alpha
    pool: backup1
    compression: lz4
    mountpoint: /mnt/backups/memory-alpha
    state: present
  - name: argus-array
    pool: backup1
    compression: lz4
    mountpoint: /mnt/backups/argus-array
    state: present

### exterrestris.sanoid
sanoid_datasets:
  - name: backup1/memory-alpha
    templates: backups
    recursive: yes
  - name: backup1/argus-array
    templates: backups
    recursive: yes

### mount_disks
parity_disks:
data_disks:
other_disks:
ntfs_data_disks:

other_mounts:
  - path: /mnt/zfs
  - path: /mnt/backups

remove_mounts:

### tigattack.mergerfs
mergerfs_mounts: []

### vladgh.samba.server
samba_shares: []
