---
ansible_host: 192.168.5.148
target_os: ubuntu

### mrlesmithjr.zfs
zfs_pools:
  - name: backup1
    action: 'create'
    compression: 'lz4'
    devices:
      # USB dock doesn't expose disk IDs - using partition UUIDs
      - '1d63c541-3a7b-45ce-a2a2-dc96cecf8d11'
      - 'c2101a06-81ad-4194-b32f-3962b92b9b00'
    type: 'mirror'
    state: 'present'

zfs_filesystems: []

### exterrestris.sanoid
sanoid_datasets:
  - name: backup1/backups
    templates: backups
  - name: backup1/backups/computers
    templates: backups
  - name: backup1/backups/drives
    templates: backups
  - name: backup1/archive
    templates: backups

### mount_disks
parity_disks:
  - path: /mnt/ext4/parity1
    diskbyid: /dev/disk/by-uuid/a8a450d1-c9cd-4a9d-a904-138b793e5135
    fs: ext4
    opts: defaults
    content: true

data_disks:
  - path: /mnt/ext4/backups1
    data_path: /data
    diskbyid: /dev/disk/by-uuid/e5a631ba-6896-46d8-a947-aec2a745e697
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/ext4/backups2
    data_path: /data
    diskbyid: /dev/disk/by-uuid/e9585a85-0247-4d0d-ae2c-cb5e83fea1eb
    fs: ext4
    opts: defaults
    content: true

other_disks:

ntfs_data_disks:

other_mounts:
  - path: /mnt/zfs

remove_mounts:

### sprat.ansible-role-mergerfs
mergerfs_mounts:
  - path: /mnt/backups
    branches:
      - /mnt/ext4/backups*/data
    options: "{{ mergerfs_opts }},category.create={{ mergerfs_policy }},x-systemd.requires=/mnt/ext4/backups1,x-systemd.requires=/mnt/ext4/backups2"

### bertvv.samba
samba_shares:
  - name: Archive
    path: /mnt/zfs/archive
    owner: "{{ main_user.username }}"
    group: archive
    mode: '2775'
    writable: 'no'
    guest_ok: 'yes'
  - name: Backups
    path: /mnt/zfs/backups
    owner: "{{ main_user.username }}"
    group: backups
    mode: '2775'
    writable: 'no'
    guest_ok: 'yes'
  - name: Old Backups
    path: /mnt/backups
    owner: "{{ main_user.username }}"
    group: backups
    mode: '2775'
    writable: 'no'
    guest_ok: 'yes'


### ironicbadger.ansible_role_snapraid
snapraid_email_address: "memory-beta@{{ internal_domain }}"
snapraid_content: ''
