---
ansible_host: 192.168.5.148
target_os: ubuntu

### mrlesmithjr.zfs
zfs_pools:
  - name: backup1
    action: 'create'
    compression: 'lz4'
    devices:
      # USB dock doesn't expose disk IDs - using partition UUIDs
      - '1d63c541-3a7b-45ce-a2a2-dc96cecf8d11'
      - 'c2101a06-81ad-4194-b32f-3962b92b9b00'
    type: 'mirror'
    state: 'present'
  - name: backup2
    action: 'create'
    compression: 'lz4'
    devices:
      # USB dock doesn't expose disk IDs - using partition UUIDs
      - 'f6fafa6d-897e-4129-97eb-979ea3957329'
      - 'a6a86991-75dd-430e-921a-f2839bb38da8'
    type: 'mirror'
    state: 'present'

zfs_filesystems:
  - name: backups
    pool: backup1
    compression: lz4
    mountpoint: /mnt/zfs/backups1
    state: present
  - name: backups/memory-alpha
    pool: backup1
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups1/memory-alpha
    state: present
  - name: backups
    pool: backup2
    compression: lz4
    mountpoint: /mnt/zfs/backups2
    state: present
  - name: backups/memory-alpha
    pool: backup2
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups2/memory-alpha
    state: present
  - name: backups/argus-array
    pool: backup2
    compression: lz4
    recordsize: 1M
    mountpoint: /mnt/zfs/backups2/argus-array
    state: present

### exterrestris.sanoid
sanoid_datasets:
  - name: backup1/archive
    templates: backups
  - name: backup1/backups/memory-alpha
    templates: backups
  - name: backup1/backups/memory-alpha/computers
    templates: backups
  - name: backup2/backups/memory-alpha
    templates: backups
  - name: backup2/backups/memory-alpha/appdata
    templates: backups
  - name: backup2/backups/memory-alpha/drives
    templates: backups

### mount_disks
parity_disks:
data_disks:
other_disks:
ntfs_data_disks:

other_mounts:
  - path: /mnt/zfs

remove_mounts:

### sprat.ansible-role-mergerfs
mergerfs_mounts:
  - path: /mnt/backups
    branches:
      - /mnt/zfs/backups*
    options: "{{ mergerfs_opts }},category.create={{ mergerfs_policy }}"

### bertvv.samba
samba_shares:
  - name: Archive
    path: /mnt/zfs/archive
    owner: "{{ main_user.username }}"
    group: archive
    mode: '2775'
    writable: 'no'
    guest_ok: 'yes'
  - name: Backups
    path: /mnt/backups
    owner: "{{ main_user.username }}"
    group: backups
    mode: '2775'
    writable: 'no'
    guest_ok: 'yes'
