---
zfs_additional_packages:
  - name: smartmontools
  - name: nvme-cli

### mrlesmithjr.zfs
zfs_create_pools: true
zfs_import_pools: true
zfs_create_filesystems: true
zfs_enable_auto_snapshots: false
zfs_manage_filesystem_permissions: true

### exterrestris.sanoid
sanoid_templates:
  - name: standard
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 28
    weekly: 6
    monthly: 3
    yearly: 0
    autosnap: 'yes'
  - name: basic
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 14
    weekly: 4
    monthly: 2
    yearly: 0
    autosnap: 'yes'
  - name: minimal
    autoprune: 'yes'
    frequently: 0
    hourly: 0
    daily: 14
    weekly: 0
    monthly: 0
    yearly: 0
    autosnap: 'yes'
  - name: interim
    autoprune: 'yes'
    frequently: 4
    hourly: 12
    daily: 14
    weekly: 0
    monthly: 0
    yearly: 0
    autosnap: 'yes'
  - name: enhanced
    autoprune: 'yes'
    frequently: 8
    hourly: 48
    daily: 28
    weekly: 6
    monthly: 3
    yearly: 0
    autosnap: 'yes'
  - name: docker
    autoprune: 'yes'
    frequently: 24
    hourly: 48
    daily: 28
    weekly: 6
    monthly: 6
    yearly: 0
    autosnap: 'yes'
  - name: backups
    autoprune: 'yes'
    frequently: 6
    hourly: 24
    daily: 14
    weekly: 12
    monthly: 12
    yearly: 0
    autosnap: 'no'
  - name: ignore
    autoprune: 'no'
    autosnap: 'no'
    monitor: 'no'

syncoid_send_options: 'L'
