---
- name: generate custom scripts
  template:
    src: "{{ script.template }}"
    dest: "{{ container.container }}.custom.d/custom-cont-init.d/{{ script.script }}"
    owner: root
    group: root
    mode: '744'
  vars:
    template_vars: "{{ script.template_vars }}"
  loop: "{{ container.scripts }}"
  loop_control:
    loop_var: script
