---
ansible_host: 192.168.5.149
target_os: ubuntu

appdata_dataset:
  name: appdata
  pool: data1
  compression: lz4
  mountpoint: /mnt/appdata
  state: present

appdata_path: "{{ appdata_dataset.mountpoint }}"

### mrlesmithjr.zfs
zfs_pools:
  - name: data1
    action: 'create'
    import: force
    compression: 'lz4'
    devices:
      # WD_Red_SN700_1000GB_24112Y801074
      - 'nvme-WD_Red_SN700_1000GB_24112Y801074'
      # WD_Red_SN700_1000GB_24112Y801475
      - 'nvme-WD_Red_SN700_1000GB_24112Y801475'
    type: 'mirror'
    properties:
      ashift: 12
      autoexpand: 'on'
    state: 'present'

zfs_datasets:
  - "{{ appdata_dataset }}"

zfs_filesystems: "{{ zfs_datasets + docker_datasets }}"

### exterrestris.sanoid
sanoid_datasets:
  - name: data1/appdata
    templates: docker
    recursive: yes

syncoid_syncs:
  - name: backup-appdata
    src: data1/appdata
    recursive: yes
    dest: backup1/argus-array/appdata
    dest_host: "memory-beta.{{ internal_domain }}"
    send_options: ''
    healthchecks:
      slug: argus-array-backup-appdata

### exterrestris.docker_compose
compose_projects:
  - name: uptime-kuma
    project_dir: "{{ appdata_dataset.mountpoint }}/uptime-kuma"
    services:
      - name: uptime-kuma
        container_name: uptime-kuma
        image:
          name: louislam/uptime-kuma
          tag: 2
        environment:
          - PUID={{ (container_users | selectattr('username', 'equalto', 'uptime-kuma') | list | first).uid }}
          - PGID={{ (container_users | selectattr('username', 'equalto', 'uptime-kuma') | list | first).gid }}
        volumes:
          - source: uptime-kuma
            target: /app/data
            group: uptime-kuma
            owner: uptime-kuma
            mode: "755"
        expose:
          - 3001
        networks:
          - proxy
        restart: always
        labels:
          - "traefik.enable=true"
          ## Router
          - "traefik.http.routers.uptime-kuma.entryPoints=https"
          - "traefik.http.routers.uptime-kuma.rule=Host(`uptime.{{ internal_domain }}`,`status.{{ internal_domain }}`)"
          - "traefik.http.routers.uptime-kuma.tls=true"
          ## Service
          - "traefik.http.services.uptime-kuma-svc.loadBalancer.server.port=3001"
          - "traefik.http.services.uptime-kuma-svc.loadbalancer.server.scheme=http"
          - "traefik.http.services.uptime-kuma-svc.loadBalancer.passHostHeader=true"
    networks:
      - name: proxy
        external: true
        alias: "{{ traefik_docker_network }}"
  - name: healthchecks
    project_dir: "{{ appdata_dataset.mountpoint }}/healthchecks"
    services:
      - name: healthchecks
        container_name: healthchecks
        image:
          name: linuxserver/healthchecks
        environment:
          - PUID={{ (container_users | selectattr('username', 'equalto', 'healthchecks') | list | first).uid }}
          - PGID={{ (container_users | selectattr('username', 'equalto', 'healthchecks') | list | first).gid }}
          - TZ=Etc/UTC
          - SITE_ROOT=https://healthchecks.{{ internal_domain }}
          - SITE_NAME=Healthchecks
          - SUPERUSER_EMAIL=sean@terrestris.co.uk
          - SUPERUSER_PASSWORD={{ vault_healthchecks_superuser_password }}
          # - ALLOWED_HOSTS=
          - APPRISE_ENABLED=True # Must be capitalised
          # - CSRF_TRUSTED_ORIGINS=
          - DEBUG=False # Must be capitalised
          - DEFAULT_FROM_EMAIL=healthchecks@{{ internal_domain }}
          - EMAIL_HOST={{ migadu_smtp_server }}
          - EMAIL_PORT={{ migadu_smtp_tls_port }}
          - EMAIL_HOST_USER=healthchecks@{{ internal_domain }}
          - EMAIL_HOST_PASSWORD={{ vault_healthchecks_migadu_user_password }}
          - EMAIL_USE_TLS=True # Must be capitalised
          - INTEGRATIONS_ALLOW_PRIVATE_IPS=True # Must be capitalised
          # - PING_EMAIL_DOMAIN=
          # - RP_ID=
          # - SECRET_KEY=
          # - SITE_LOGO_URL=
        volumes:
          - source: healthchecks
            target: /config
            group: healthchecks
            owner: healthchecks
            mode: "755"
        expose:
          - 8000
        networks:
          - proxy
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          ## Router
          - "traefik.http.routers.healthchecks.entryPoints=https"
          - "traefik.http.routers.healthchecks.rule=Host(`healthchecks.{{ internal_domain }}`)"
          - "traefik.http.routers.healthchecks.tls=true"
          ## Service
          - "traefik.http.services.healthchecks-svc.loadBalancer.server.port=8000"
          - "traefik.http.services.healthchecks-svc.loadbalancer.server.scheme=http"
          - "traefik.http.services.healthchecks-svc.loadBalancer.passHostHeader=true"
    networks:
      - name: proxy
        external: true
        alias: "{{ traefik_docker_network }}"
  - name: dozzle
    project_dir: "{{ appdata_dataset.mountpoint }}/dozzle"
    services:
      - name: dozzle
        image:
          name: ghcr.io/amir20/dozzle
          tag: v10
        expose:
          - 8080
        networks:
          - proxy
        volumes:
          - source: /var/run/docker.sock
            target: /var/run/docker.sock
            type: socket
        environment:
          - DOZZLE_REMOTE_AGENT={{ hostvars['memory_alpha']['ansible_hostname'] }}.{{ internal_domain }}:7007
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          ## Router
          - "traefik.http.routers.dozzle.entryPoints=https"
          - "traefik.http.routers.dozzle.rule=Host(`dozzle.{{ internal_domain }}`)"
          - "traefik.http.routers.dozzle.tls=true"
          ## Service
          - "traefik.http.services.dozzle-svc.loadBalancer.server.port=8080"
          - "traefik.http.services.dozzle-svc.loadbalancer.server.scheme=http"
          - "traefik.http.services.dozzle-svc.loadBalancer.passHostHeader=true"
    networks:
      - name: proxy
        external: true
        alias: "{{ traefik_docker_network }}"
  - name: n8n
    project_dir: "{{ appdata_dataset.mountpoint }}/n8n"
    services:
      - name: n8n
        image:
          name: docker.n8n.io/n8nio/n8n
          tag: 2.10.3
        user:
          groups:
            - "{{ (container_users | selectattr('username', 'equalto', 'n8n') | list | first).gid }}"
        environment:
          - GENERIC_TIMEZONE=Europe/London
          - TZ=Europe/London
          - DB_TYPE=postgresdb
          - DB_POSTGRESDB_HOST=postgres
          - DB_POSTGRESDB_PORT=5432
          - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
          - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
          - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
          - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
          - N8N_HOST=n8n.{{ internal_domain }}
          - N8N_PROTOCOL=https
          - N8N_RUNNERS_MODE=external
          - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
          - WEBHOOK_URL=https://n8n.{{ internal_domain }}/
        env_file:
          - data: |
              N8N_RUNNERS_AUTH_TOKEN={{ vault_n8n_runner_token }}
        volumes:
          - source: n8n
            target: /home/node/.n8n
            group: n8n
            owner: n8n
            mode: 2775
        expose:
          - 5678
        networks:
          - n8n
          - proxy
        restart: unless-stopped
        links:
          - postgres
        depends_on:
          postgres:
            condition: service_healthy
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network={{ traefik_docker_network }}"
          ## Router
          - "traefik.http.routers.n8n.entryPoints=https"
          - "traefik.http.routers.n8n.rule=Host(`n8n.{{ internal_domain }}`)"
          - "traefik.http.routers.n8n.tls=true"
          - "traefik.http.routers.n8n.middlewares=n8n@docker"
          ## Middlewares
          - "traefik.http.middlewares.n8n.headers.SSLRedirect=true"
          - "traefik.http.middlewares.n8n.headers.STSSeconds=315360000"
          - "traefik.http.middlewares.n8n.headers.browserXSSFilter=true"
          - "traefik.http.middlewares.n8n.headers.contentTypeNosniff=true"
          - "traefik.http.middlewares.n8n.headers.forceSTSHeader=true"
          # - traefik.http.middlewares.n8n.headers.SSLHost={{ internal_domain }}
          - "traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true"
          - "traefik.http.middlewares.n8n.headers.STSPreload=true"
          ## Service
          - "traefik.http.services.n8n-svc.loadBalancer.server.port=5678"
          - "traefik.http.services.n8n-svc.loadbalancer.server.scheme=http"
          - "traefik.http.services.n8n-svc.loadBalancer.passHostHeader=true"
      - name: n8n-runners
        image:
          name: n8nio/runners
          tag: 2.10.3
        environment:
          - N8N_RUNNERS_TASK_BROKER_URI=http://n8n:5679
        env_file:
          - data: |
              N8N_RUNNERS_AUTH_TOKEN={{ vault_n8n_runner_token }}
        networks:
          - n8n
        depends_on:
          - n8n
        labels:
          - "traefik.enable=false"
      - name: postgres
        image:
          name: postgres
          tag: 16
        user:
          user: "{{ (container_users | selectattr('username', 'equalto', 'postgres') | list | first).uid }}"
          group: "{{ (container_users | selectattr('username', 'equalto', 'postgres') | list | first).gid }}"
        environment:
          - GENERIC_TIMEZONE=Europe/London
          - TZ=Europe/London
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}
          - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
        volumes:
          - source: postgres/data
            target: /var/lib/postgresql/data
            owner: postgres
            group: postgres
            mode: 2700
          # From https://raw.githubusercontent.com/n8n-io/n8n-hosting/refs/heads/main/docker-compose/withPostgres/init-data.sh
          - source: postgres/init-data.sh
            target: /docker-entrypoint-initdb.d/init-data.sh
            data: !unsafe |
              #!/bin/bash
              set -e;
              
              if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
              	psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
              	        CREATE USER ${POSTGRES_NON_ROOT_USER} WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
              	        GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_NON_ROOT_USER};
              	        GRANT CREATE ON SCHEMA public TO ${POSTGRES_NON_ROOT_USER};
              	EOSQL
              else
              	echo "SETUP INFO: No Environment variables given!"
              fi
            owner: postgres
            group: postgres
            mode: 440
        healthcheck:
          test: "['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']"
          interval: 5s
          timeout: 5s
          retries: 10
        networks:
          - n8n
        restart: unless-stopped
        labels:
          - "traefik.enable=false"
    env_file:
      data: |
        POSTGRES_DB=n8n
        POSTGRES_USER={{ vault_n8n_db_root_user }}
        POSTGRES_PASSWORD={{ vault_n8n_db_root_password }}
        POSTGRES_NON_ROOT_USER={{ vault_n8n_db_user }}
        POSTGRES_NON_ROOT_PASSWORD={{ vault_n8n_db_password }}
    networks:
      - name: n8n
      - name: proxy
        external: true
        alias: "{{ traefik_docker_network }}"
  - name: speedtest-tracker
    project_dir: "{{ appdata_dataset.mountpoint }}/speedtest-tracker"
    services:
      - name: speedtest-tracker
        image:
          name: lscr.io/linuxserver/speedtest-tracker
          tag: latest
        environment:
          - GENERIC_TIMEZONE=Europe/London
          - TZ=Europe/London
          - PUID={{ (container_users | selectattr('username', 'equalto', 'speedtest-tracker') | list | first).uid }}
          - PGID={{ (container_users | selectattr('username', 'equalto', 'speedtest-tracker') | list | first).gid }}
          - APP_URL=https://speedtest.{{ internal_domain }}/
          - ASSET_URL=https://speedtest.{{ internal_domain }}/
          - DB_CONNECTION=pgsql
          - DB_HOST=db
          - DB_PORT=5432
          - DB_DATABASE=${POSTGRES_DB}
          - DB_USERNAME=${POSTGRES_USER}
          - DB_PASSWORD=${POSTGRES_PASSWORD}
          - SPEEDTEST_SCHEDULE=8 */2 * * *
        env_file:
          - data: |
              APP_KEY={{ vault_speedtest_app_key }}
        volumes:
          - source: config
            target: /config
            group: speedtest-tracker
            owner: speedtest-tracker
            mode: 2775
        expose:
          - 80
        networks:
          - speedtest-tracker
          - proxy
        restart: unless-stopped
        depends_on:
          db:
            condition: service_healthy
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network={{ traefik_docker_network }}"
          ## Router
          - "traefik.http.routers.speedtest-tracker.entryPoints=https"
          - "traefik.http.routers.speedtest-tracker.rule=Host(`speedtest.{{ internal_domain }}`)"
          - "traefik.http.routers.speedtest-tracker.tls=true"
          ## Service
          - "traefik.http.services.speedtest-tracker-svc.loadBalancer.server.port=80"
          - "traefik.http.services.speedtest-tracker-svc.loadbalancer.server.scheme=http"
          - "traefik.http.services.speedtest-tracker-svc.loadBalancer.passHostHeader=true"
      - name: db
        image:
          name: postgres
          tag: 18
        user:
          user: "{{ (container_users | selectattr('username', 'equalto', 'postgres') | list | first).uid }}"
          group: "{{ (container_users | selectattr('username', 'equalto', 'postgres') | list | first).gid }}"
        environment:
          - GENERIC_TIMEZONE=Europe/London
          - TZ=Europe/London
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
          - source: postgres
            target: /var/lib/postgresql
            owner: postgres
            group: postgres
            mode: 2700
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
          interval: 10s
          timeout: 5s
          retries: 5
        networks:
          - speedtest-tracker
        restart: unless-stopped
        labels:
          - "traefik.enable=false"
    env_file:
      data: |
        POSTGRES_DB=speedtest-tracker
        POSTGRES_USER={{ vault_speedtest_db_user }}
        POSTGRES_PASSWORD={{ vault_speedtest_db_password }}
    networks:
      - name: speedtest-tracker
      - name: proxy
        external: true
        alias: "{{ traefik_docker_network }}"
  - name: omada-controller
    project_dir: "{{ appdata_dataset.mountpoint }}/omada-controller"
    services:
      - name: omada-controller
        container_name: omada-controller
        image:
          name: mbentley/omada-controller
        ports:
          - port: 8088
          - port: 8043
          - port: 8843
          - port: 27001
            protocol: udp
          - port: 29810
            protocol: udp
          - port: 29811
          - port: 29812
          - port: 29813
          - port: 29814
        environment:
          - PUID={{ (container_users | selectattr('username', 'equalto', 'omada') | list | first).uid }}
          - PGID={{ (container_users | selectattr('username', 'equalto', 'omada') | list | first).gid }}
          - MANAGE_HTTP_PORT=8088
          - MANAGE_HTTPS_PORT=8043
          - PORTAL_HTTP_PORT=8088
          - PORTAL_HTTPS_PORT=8843
          - PORT_APP_DISCOVERY=27001
          - PORT_ADOPT_V1=29812
          - PORT_UPGRADE_V1=29813
          - PORT_MANAGER_V1=29811
          - PORT_MANAGER_V2=29814
          - PORT_DISCOVERY=29810
          - SHOW_SERVER_LOGS=true
          - SHOW_MONGODB_LOGS=false
          #- SSL_CERT_NAME=tls.crt
          #- SSL_KEY_NAME=tls.key
          - TZ=Etc/UTC
        volumes:
          - source: omada-controller/data
            target: /opt/tplink/EAPController/data
            group: omada
            owner: omada
            mode: "755"
          - source: omada-controller/logs
            target: /opt/tplink/EAPController/logs
            group: omada
            owner: omada
            mode: "755"
        restart: always
