---
traefik_docker_network_bridge_name: br-traefik0

### exterrestris.traefik
traefik_log_enabled: yes
traefik_config_dir: "{{ appdata_path }}/traefik"
traefik_dashboard_domain: "traefik.{{ ansible_hostname }}.{{ internal_domain }}"
traefik_tls_certificates:
  - cert: "/etc/traefik/{{ internal_domain }}-wildcard.cert"
    key: "/etc/traefik/{{ internal_domain }}-wildcard.key"
  - cert: "/etc/traefik/{{ ansible_hostname }}.{{ internal_domain }}-wildcard.cert"
    key: "/etc/traefik/{{ ansible_hostname }}.{{ internal_domain }}-wildcard.key"
    default: yes
traefik_docker_network: traefik
traefik_docker_network_driver_options:
  com.docker.network.bridge.name: "{{ traefik_docker_network_bridge_name }}"

cockpit_traefik_service:
  name: cockpit-svc
  type: http
  servers:
    - "http://{{ ansible_hostname }}.{{ internal_domain }}:9090"

cockpit_traefik_router:
  name: cockpit
  service: "cockpit-svc@file"
  rule: "Host(`cockpit.{{ ansible_hostname }}.{{ internal_domain }}`)"

traefik_routers:
  - "{{ cockpit_traefik_router }}"
traefik_services:
  - "{{ cockpit_traefik_service }}"

### weareinteractive.ufw
cockpit_traefik_ufw_rules:
  - rule: allow
    to_port: 9090
    proto: tcp
    delete: yes
  - rule: allow
    to_port: 9090
    proto: tcp
    interface_in: "{{ traefik_docker_network_bridge_name }}"
docker_ufw_rules:
  - "{{ cockpit_traefik_ufw_rules }}"

### exterrestris.docker_compose

### exterrestris.fetch_ssl
fetch_ssl_ssh_host: "midas-array.{{ internal_domain }}"
fetch_ssl_ssh_user: admin
fetch_ssl_certs:
  - cert: "/conf/acme/{{ internal_domain }}-wildcard.fullchain"
    key: "/conf/acme/{{ internal_domain }}-wildcard.key"
    install_to:
      - cert: "{{ traefik_config_dir }}/{{ internal_domain }}-wildcard.cert"
        key: "{{ traefik_config_dir }}/{{ internal_domain }}-wildcard.key"
  - cert: "/conf/acme/{{ ansible_hostname }}.{{ internal_domain }}-wildcard.fullchain"
    key: "/conf/acme/{{ ansible_hostname }}.{{ internal_domain }}-wildcard.key"
    install_to:
      - cert: "{{ traefik_config_dir }}/{{ ansible_hostname }}.{{ internal_domain }}-wildcard.cert"
        key: "{{ traefik_config_dir }}/{{ ansible_hostname }}.{{ internal_domain }}-wildcard.key"

fetch_ssl_run_now: yes
