---
### exterrestris.traefik
traefik_install: binary
traefik_log_enabled: yes
traefik_dashboard_domain: "traefik.{{ ansible_hostname }}.{{ internal_domain }}"
traefik_tls_certificates:
  - cert: "{{ internal_domain }}-wildcard.cert"
    key: "{{ internal_domain }}-wildcard.key"
  - cert: "{{ ansible_hostname }}.{{ internal_domain }}-wildcard.cert"
    key: "{{ ansible_hostname }}.{{ internal_domain }}-wildcard.key"
    default: yes
traefik_providers:
  - "{{ traefik_default_file_provider }}"

### weareinteractive.ufw
traefik_ufw_rules:
  - rule: allow
    to_port: 80
    proto: tcp
  - rule: allow
    to_port: 443
    proto: tcp

### exterrestris.fetch_ssl
fetch_ssl_certificate_source: certmate
fetch_ssl_certmate_token: "{{ vault_certmate_api_token }}"
fetch_ssl_certmate_host: "certmate.{{ internal_domain }}"
fetch_ssl_certmate_cert: "{{ internal_domain }}"
fetch_ssl_certs:
  - name: "{{ internal_domain }}"
    install_to:
      - cert: "{{ traefik_tls_certificate_dir }}/{{ internal_domain }}-wildcard.cert"
        key: "{{ traefik_tls_certificate_dir }}/{{ internal_domain }}-wildcard.key"
  - name: "{{ ansible_hostname }}.{{ internal_domain }}"
    install_to:
      - cert: "{{ traefik_tls_certificate_dir }}/{{ ansible_hostname }}.{{ internal_domain }}-wildcard.cert"
        key: "{{ traefik_tls_certificate_dir }}/{{ ansible_hostname }}.{{ internal_domain }}-wildcard.key"
fetch_ssl_run_now: yes
