---
### exterrestris.traefik
traefik_config_dir: "{{ appdata_path }}/traefik"
traefik_insecure_api: true
traefik_tls_certificates:
  - cert: "{{ appdata_path }}/traefik/{{ internal_domain }}-wildcard.cert"
    key: "{{ appdata_path }}/traefik/{{ internal_domain }}-wildcard.key"

### exterrestris.fetch_ssl
fetch_ssl_ssh_host: "midas-array.{{ internal_domain }}"
fetch_ssl_ssh_user: admin
fetch_ssl_ssh_cert_path: "/conf/acme/{{ internal_domain }}-wildcard.fullchain"
fetch_ssl_ssh_key_path: "/conf/acme/{{ internal_domain }}-wildcard.key"
fetch_ssl_run_now: yes
fetch_ssl_install_to:
  - cert: "{{ appdata_path }}/traefik/{{ internal_domain }}-wildcard.cert"
    key: "{{ appdata_path }}/traefik/{{ internal_domain }}-wildcard.key"