---
### exterrestris.traefik
traefik_install: binary
traefik_log_enabled: yes
traefik_dashboard_domain: "traefik.{{ ansible_hostname }}.{{ internal_domain }}"
traefik_tls_certificates:
  - cert: "{{ internal_domain }}-wildcard.cert"
    key: "{{ internal_domain }}-wildcard.key"
  - cert: "{{ ansible_hostname }}.{{ internal_domain }}-wildcard.cert"
    key: "{{ ansible_hostname }}.{{ internal_domain }}-wildcard.key"
    default: yes
traefik_providers:
  - "{{ traefik_default_file_provider }}"

cockpit_traefik_service:
  name: cockpit-svc
  type: http
  servers:
    - "http://{{ ansible_hostname }}.{{ internal_domain }}:9090"

cockpit_traefik_router:
  name: cockpit
  service: "cockpit-svc@file"
  rule: "Host(`cockpit.{{ ansible_hostname }}.{{ internal_domain }}`)"
  entrypoints:
    - http
    - https

traefik_routers:
  - "{{ cockpit_traefik_router }}"
traefik_services:
  - "{{ cockpit_traefik_service }}"

### weareinteractive.ufw
cockpit_traefik_ufw_rules:
  - rule: allow
    to_port: 9090
    proto: tcp
    delete: yes

traefik_ufw_rules:
  - rule: allow
    to_port: 80
    proto: tcp
  - rule: allow
    to_port: 443
    proto: tcp

### exterrestris.fetch_ssl
fetch_ssl_ssh_host: "midas-array.{{ internal_domain }}"
fetch_ssl_ssh_user: admin
fetch_ssl_certs:
  - cert: "/conf/acme/{{ internal_domain }}-wildcard.fullchain"
    key: "/conf/acme/{{ internal_domain }}-wildcard.key"
    install_to:
      - cert: "{{ traefik_tls_certificate_dir }}/{{ internal_domain }}-wildcard.cert"
        key: "{{ traefik_tls_certificate_dir }}/{{ internal_domain }}-wildcard.key"
  - cert: "/conf/acme/{{ ansible_hostname }}.{{ internal_domain }}-wildcard.fullchain"
    key: "/conf/acme/{{ ansible_hostname }}.{{ internal_domain }}-wildcard.key"
    install_to:
      - cert: "{{ traefik_tls_certificate_dir }}/{{ ansible_hostname }}.{{ internal_domain }}-wildcard.cert"
        key: "{{ traefik_tls_certificate_dir }}/{{ ansible_hostname }}.{{ internal_domain }}-wildcard.key"

fetch_ssl_run_now: yes
