---
ansible_host: 192.168.5.136
target_os: ubuntu

### exterrestris.traefik
traefik_binary_version: v2.6.3

traefik_access_log_enabled: yes

traefik_internal_entrypoint:
  host: "{{ ansible_enp6s18.ipv4.address }}"

traefik_external_entrypoint:
  host: "{{ ansible_enp6s19.ipv4.address }}"

traefik_entrypoints:
  - "{{ traefik_default_http_entrypoint | combine(traefik_internal_entrypoint) }}"
  - "{{ traefik_default_https_entrypoint | combine(traefik_internal_entrypoint) }}"
  - name: web-http
    port: 80
    host: "{{ ansible_enp6s19.ipv4.address }}"
    http:
      redirect:
        to: web-https
        scheme: 'https'
  - name: web-https
    port: 443
    host: "{{ ansible_enp6s19.ipv4.address }}"

traefik_routers:
  - "{{ cockpit_traefik_router }}"
  - name: jellyfin-proxy
    service: "jellyfin-proxy-svc@file"
    rule: "Host(`jellyfin.{{ internal_domain }}`)"
    entrypoints:
      - web-http
      - web-https
  - name: ombi-proxy
    service: "ombi-proxy-svc@file"
    rule: "Host(`ombi.{{ internal_domain }}`)"
    entrypoints:
      - web-http
      - web-https
  - name: status-proxy
    service: "status-proxy-svc@file"
    rule: "Host(`status.{{ internal_domain }}`)"
    entrypoints:
      - web-http
      - web-https
      - http
      - https

traefik_services:
  - "{{ cockpit_traefik_service }}"
  - name: jellyfin-proxy-svc
    type: http
    servers:
      - "https://jellyfin.{{ internal_domain }}"
  - name: ombi-proxy-svc
    type: http
    servers:
      - "https://ombi.{{ internal_domain }}"
  - name: status-proxy-svc
    type: http
    servers:
      - "https://uptime.{{ internal_domain }}"
